import argparse

parser = argparse.ArgumentParser(description='Holy Shit! The code is running!')
parser.add_argument('--dataset', default='Flythings3D', choices=['CrabCage', 'Monkaa', 'Flythings3D'])
parser.add_argument('--img-size', default=518, type=int)
parser.add_argument('--total-steps', default=200000, type=int)
parser.add_argument('--warm-up-step', default=999999999, type=int)
parser.add_argument('--bs', default=4, type=int)
parser.add_argument('--lr', default=1e-5, type=float)
parser.add_argument('--num-workers', default=4, type=int)
parser.add_argument('--pretrained-from', type=str, default='checkpoints')
parser.add_argument('--save-path', type=str, default='outputs')
parser.add_argument('--val-interval', default=500, type=int)
parser.add_argument('--max-depth', default=600, type=int)
parser.add_argument('--min-depth', default=0.001, type=float)
parser.add_argument('--max-disp', default=550, type=int)
parser.add_argument('--min-disp', default=0.001, type=float)
parser.add_argument('--eval-target-area', type=bool, default=True)
parser.add_argument('--max-val-samples', default=100, type=int)

parser.add_argument('--encoder', default='vits', choices=['vits', 'vitb', 'vitl', 'vitg'])
parser.add_argument('--gru_iters', type=int, default=24)
parser.add_argument('--disp_init_var', type=float, default=4.0) 
parser.add_argument('--corr_implementation', type=str, default='')
parser.add_argument('--corr_levels', type=int, default=4)
parser.add_argument('--corr_radius', type=int, default=4)
parser.add_argument('--n_downsample', type=int, default=3)
parser.add_argument('--n_gru_layers', type=int, default=3)
parser.add_argument('--context_norm', type=str, default="batch", choices=['group', 'batch', 'instance', 'none'], help="normalization of context encoder")
parser.add_argument('--hidden_dims', nargs=3, type=int, default=[128, 128, 128])
parser.add_argument('--saturation_range', nargs=2, type=float, default=[0.0, 1.4])
parser.add_argument('--spatial_scale', nargs=2, type=float, default=[-0.2, 0.4])
parser.add_argument('--noyjitter', type=bool, default=True)
parser.add_argument('--num_gpu', type=int, default=4)

parser.add_argument('--target_loss_enhance', type=bool, default=True)
parser.add_argument('--use_roi_attn', type=bool, default=True)
parser.add_argument('--beat_repetitive-texture', type=bool, default=True)
parser.add_argument('--use_grad_modulator', type=bool, default=True)

parser.add_argument('--restore_checkpoint', type=str, default='outputs/20260419_102341/step_000004500/checkpoint.pth')

args, unknown = parser.parse_known_args()
